name: RewardPlugin
main: net.wajwuz.rewards.basic.RewardPlugin
version: ${project.version}
authors: [wajwuz, memehuj]
website: http://wajwuz.club
description: A simple discord reward plugin
softdepend:
  - PlaceholderAPI