name: RewardPlugin
main: net.wajwuz.rewards.basic.RewardPlugin
version: 1.0-SNAPSHOT
authors: [wajwuz, memehuj]
website: http://wajwuz.club
description: A simple discord reward plugin
softdepend:
  - PlaceholderAPI